administrator/com_joomgallery/tmpl/categories/default.php, administrator/com_joomgallery/tmpl/images/default.php
Since joomla 4.2 there is a nice feature to hide any column in the table views: https://github.com/joomla/joomla-cms/pull/36591
@szepty-ziemi had already suggested the implementation at the last online meeting.
Surprisingly, the implementation in the JoomGallery was very simple.
Used for categories and images view because in tags and configuration view there are only a few columns.
=> Add Hide Table Columns for categories and images

administrator/com_joomgallery/src/View/Categories/HtmlView.php, administrator/com_joomgallery/src/View/Configs/HtmlView.php, administrator/com_joomgallery/src/View/Images/HtmlView.php, administrator/com_joomgallery/src/View/Tags/HtmlView.php
Possible fix for https://github.com/JoomGalleryfriends/JG4-dev/issues/11
The toolbar buttons now have the same order and identical names in all managers:
- New
- Batch
- Duplicate
- ...
- State
- Publish
- Unpublish
- Delete
@Elfangor93 Do we need a 'state' (Publish) column for configuration(s) or can this column deleted?
=> Reorganise toolbar buttons

administrator/com_joomgallery/forms/category.xml, administrator/com_joomgallery/forms/filter_categories.xml, administrator/com_joomgallery/forms/filter_images.xml, administrator/com_joomgallery/forms/image.xml, administrator/com_joomgallery/language/en-GB/com_joomgallery.ini, administrator/com_joomgallery/layouts/joomla/form/field/jgcategory.php, administrator/com_joomgallery/src/Field/JgcategoryField.php, administrator/com_joomgallery/src/Field/JgcategorydropdownField.php, administrator/com_joomgallery/src/Model/CategoriesModel.php, administrator/com_joomgallery/src/Model/CategoryModel.php, administrator/com_joomgallery/tmpl/categories/modal.php, media/com_joomgallery/joomla.asset.json, media/com_joomgallery/js/field-category.js
It adds a new field to JoomGallery which allows to select a JoomGallery category using a modal box.
Clicking the button opens a modal box where you can search for the category. A click on the category name closes the modal and sets the category as new value in the field.
The field is used in the category edit form to select a parent category.
Go to category manager, edit a category and select a parent category. Use filter and sorting options in the provided modal box to search for the correct category in your gallery.
=> New field: JG-Category selection

administrator/com_joomgallery/tmpl/categories/default.php, administrator/com_joomgallery/tmpl/images/default.php, administrator/com_joomgallery/tmpl/tags/default.php
Fix Warning: Undefined variable $saveOrderingUrl ...
in images, categories and tags manager
Go to image manager, category manager or tags manager.
Set sorting to 'ordering ascending'.
Apply a filter so that no item is found. Maybe access is 'Special' or like something.
A empty list or the message 'No Matching Results' like in Joomla should be shown.
A warning is shown: Warning: Undefined variable $saveOrderingUrl ...
=> Fix warning missing variable $saveOrderingUrl

administrator/com_joomgallery/src/View/Category/HtmlView.php, administrator/com_joomgallery/src/View/Config/HtmlView.php, administrator/com_joomgallery/src/View/Image/HtmlView.php, administrator/com_joomgallery/src/View/Tag/HtmlView.php
In edit forms Joomla! groups 'Save & Close', 'Save & New' and 'Save as Copy' as a dropdown.
This pr do this in the same way.
=> Group action buttons in edit forms

administrator/com_joomgallery/src/Service/IMGtools/IMtools.php
Fix two problems with image processor ImageMagick:
- Fixes problem "Unsupported image filetype". 
See https://github.com/JoomGalleryfriends/JG4-dev/issues/62 and https://github.com/JoomGalleryfriends/JG4-dev/issues/36
When using Imagemagick v6.x, the supported image types are not detected correctly.
- Fixes problem with quality parameter. 
Currently, the quality parameter from the configuration was not respected.
This PR should fix both problems.
=> Fix problems with image processor ImageMagick

administrator/com_joomgallery/src/Service/IMGtools/GDtools.php
The function checkMemory checks the value of memory_limit which is set in php.ini. Some hosters have set a value of -1 here. This 'unusual' value causes the check to fail.
This is a redo from https://github.com/JoomGalleryfriends/JoomGallery/pull/123
=> Fix error when memory_limit is set to -1

administrator/com_joomgallery/forms/category.xml, administrator/com_joomgallery/forms/image.xml
Rename the field from 'created by' to 'owner' for images and categories as discussed here: https://github.com/JoomGalleryfriends/JG4-dev/issues/65
Only the 'displayed' name based on the language key is changed. 
The field in the database table itself has not been renamed, otherwise this would require larger changes.
=> Rename field 'created by' to 'owner' 

administrator/com_joomgallery/forms/filter_images.xml, administrator/com_joomgallery/language/en-GB/com_joomgallery.ini, administrator/com_joomgallery/src/Field/UserdropdownField.php
@eumel1602  has reported here that there is a visual problem in the image manager:
https://github.com/JoomGalleryfriends/JG4-dev/pull/83#issuecomment-1486721378
In some selectboxes the texts are too long and cause a visual problem.
This PR fixes the problem by using the shorter texts as in Joomla itself. See texts in Joomla article manager.
I have tried to change the language constants in the forms/filter_images.xml. Unfortunately, this does not work.
For Category Select Box:
The previous text "Type or Select a Category" is loaded via the language constant JGLOBAL_TYPE_OR_SELECT_CATEGORY. This constant is used in line 71 of .../com_categories/layouts/form/field/categoryedit.php.
To shorten the text I only see the possibility to redefine the constant JGLOBAL_TYPE_OR_SELECT_CATEGORY in the …
=> Solve visual problems in image manager

administrator/com_joomgallery/src/Service/IMGtools/GDtools.php, administrator/com_joomgallery/src/Table/CategoryTable.php, administrator/com_joomgallery/src/Table/ConfigTable.php, administrator/com_joomgallery/src/Table/ImageTable.php, administrator/com_joomgallery/src/Table/TagTable.php
When using PHP 8.1 and Error Reporting = Maximum, there are PHP Deprecated messages.
These warning messages cause e.g. in the image manager that no thumbnails are displayed.
The problem is always the bind function in which ...\strpos($task, 'save')... is used to check for the presence of a string in the '$task' variable.
If $task is NULL, however, this message appears.
Enclosed is a suggestion how to prevent this message. Maybe there is a better suggestion?
=> Fix PHP Deprecated messages when using php 8.1

.gitignore, administrator/com_joomgallery/src/Controller/ImagesController.php, administrator/com_joomgallery/src/Helper/ApprovedButton.php
Before this PR the approve button did not work korrectly. It was not possible to unapprove an image once it was approved using the images view.
With this PR this should work now.
=> Fix approve button

administrator/com_joomgallery/forms/image.xml, administrator/com_joomgallery/language/en-GB/com_joomgallery.ini, administrator/com_joomgallery/src/Controller/ImageController.php, administrator/com_joomgallery/src/Field/JgimagetypeField.php, administrator/com_joomgallery/src/Model/ImageModel.php, administrator/com_joomgallery/src/Service/FileManager/FileManager.php, administrator/com_joomgallery/src/Service/FileManager/FileManagerInterface.php, administrator/com_joomgallery/src/Service/FileManager/FileManagerServiceTrait.php, administrator/com_joomgallery/src/Service/Uploader/SingleUploader.php, administrator/com_joomgallery/src/Service/Uploader/UploaderServiceTrait.php, administrator/com_joomgallery/src/View/Image/HtmlView.php, administrator/com_joomgallery/tmpl/image/edit.php, administrator/com_joomgallery/tmpl/image/replace.php
This PR adds the functionality to replace/exchange a specific imagetype (thumbnail, detail, original, ...). This is useful for example, if you are not satisfied with an automatic processing result and you want to create the image for this imagetype locally by hand and then replace it.
In the Image edit view there is now a "Replace" button in the preview modal of each imagetype. This button brings you to a from view where you can select/upload the image used for replacement.
Replacement form view
The left side is to be filled out. The right side gives you the info on which image you are working on.
=> Replace imagetype

administrator/com_joomgallery/tmpl/image/upload.php, media/com_joomgallery/css/admin.css
Currently there are shifts in the following lines in uppy dashboard for images with long file names.
There is also an empty space between the uppy dashboard and the input fields on the right.
This PR should fix this problem.
=> Fixes a layout problem in the uppy dashboard

script.php, site/com_joomgallery/src/Model/CategoryModel.php
Currently, only (sub)categories that contain images are displayed in the category view.
This PR ensures that empty categories are also displayed.
=> Show categories without images

.gitignore, administrator/com_joomgallery/src/Table/CategoryTable.php, script.php
Upgrade from JG3 to JG4 created an error, when script tries to uninstall modules during the upgrading process. Line 180 of script.php `$this->uninstallModules(array('mod_joomgithub'));` throws an error because it tries to call method `children()` on variable type array.
Thanks @csoscd for reporting this issue.
=> Fix error in script when upgrade from JG3 to JG4

administrator/com_joomgallery/src/Service/Filesystem/Filesystem.php
Fix PHP deprected warnings:
```
PHP Deprecated:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in \administrator\components\com_joomgallery\src\Service\Filesystem\Filesystem.php on line 831
PHP Deprecated:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in \administrator\components\com_joomgallery\src\Service\Filesystem\Filesystem.php on line 839
PHP Deprecated:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in \administrator\components\com_joomgallery\src\Service\Filesystem\Filesystem.php on line 847
```
It tries to read values from the configuration that are not existent.
The code is only commented out so that it can be easily reactivated later.
See also …
=> prevent php deprecated warning

.gitignore, administrator/com_joomgallery/layouts/joomla/form/field/radio/configbtns.php, administrator/com_joomgallery/layouts/joomla/pagination/link.php, administrator/com_joomgallery/layouts/joomla/pagination/links.php, joomgallery.xml, media/com_joomgallery/css/site.css, site/com_joomgallery/layouts/joomla/pagination/link.php, site/com_joomgallery/layouts/joomla/pagination/links.php, site/com_joomgallery/layouts/joomla/searchtools/default.php, site/com_joomgallery/src/Model/CategoryModel.php, site/com_joomgallery/src/View/Category/HtmlView.php, site/com_joomgallery/tmpl/category/default.php
Extending the frontend category view.
`$this->item->parent`
Item object of the parent category. Information about the parent category.
`$this->item->children`
List of subcategory item objects. Information about the subcategories.
`$this->item->images`
List of image item objects of this category. Including pagination and filter objects to create a pagination and a filter form. 
Visit `index.php?option=com_joomgallery&view=category` (category view) in the frontend. There is now a filter form on top of the image grid and a pagination below.
=> Frontend category view

administrator/com_joomgallery/src/View/Control/HtmlView.php, joomgallery.xml
Under certain circumstances, the version info of the gallery is displayed incorrectly in the control panel.
This PR fixes this rare problem.
It also removes a duplicate entry from the joomgallery.xml:
`<plugin group="webservices" plugin="joomgallery"/>`
There's not much to test.
=> Fix wrong version info

administrator/com_joomgallery/src/Model/ImageModel.php, administrator/com_joomgallery/src/Model/JoomAdminModel.php
This is a fix for issue #101 .
New image records will not get saved anymore if there was an error during image creation.
=> Fix issue: Image record saved if error during imagetype creation

plugins/system/joomowner/src/Extension/JoomgalleryOwner.php
There was a bug in the `plg_system_joomowner` Plugin.
When saving a content type which does not have a connection to the users table, an error was thrown because the Plugin was not able to find the owner field in the table (since it does not exist in that case).
Before applying this PR, saving a configuration set ends in a PHP error.
After applying this PR saving a configuration set is successful.
=> Error in JoomOwner Plugin

administrator/com_joomgallery/src/Service/Migration/Migration.php, administrator/com_joomgallery/src/Service/Migration/Scripts/Jg3ToJg4.php
If you interrupt a migration before saving the migration configuration form the first time you get a php error because there are no params.
This PR adds default values when getting migration params to mitigate that: `$this->params->get('same_db', 1)`
Interrupting before submission of the migration configuration will throw a php error
No error is thrown
=> Fix php error when interrupt migration before step 1

administrator/com_joomgallery/src/Service/Migration/Scripts/Jg3ToJg4.php
This pr updates the maximum version of the old JoomGallery 3.x in the migration script.
=> Update max version of JG3 in migration script

administrator/com_joomgallery/language/en-GB/com_joomgallery.ini, administrator/com_joomgallery/src/Controller/MigrationController.php, administrator/com_joomgallery/src/Model/MigrationModel.php, administrator/com_joomgallery/src/Service/Migration/Migration.php
This PR fixes multiple issues reported in #201.
The following things are added/improved:
- Migration form validation for field `Joomla! path`. Checks, if the folder of the given path exists.
- Migration form validation for database fields. Checks, if a connection to the database is possible with the entered credentials.
- Fixes php error: in_array(): Argument 2 ($haystack) must be of type array, null given
Pendent:
- Migration precheck needs 20 connections to the database
=> Database connection problems

administrator/com_joomgallery/forms/image.xml
PHP 8.1: The use of the calendar field seems to generate this warning in Joomla in general.
It should be sufficient to change in the xml file to **_translateformat="true"_**. I don't know if there is a better solution?
See also: https://github.com/JoomGalleryfriends/JG4-dev/issues/131#issue-1877971439
=> Fix warning "Deprecated: Function strftime() is deprecated..." when editing images

media/com_joomgallery/joomla.asset.json
This adds back the necessary information that was deleted in pull request #123.
@MrMusic please test the pull request
=> fix masonry bug caused by #123

administrator/com_joomgallery/src/Service/IMGtools/IMtools.php
This is a fix for issue https://github.com/JoomGalleryfriends/JG4-dev/issues/221
If the 'exec' function is deactivated on the server, an error occurs when the JoomGallery configuration is opened.
Add 'exec' to the list of disabled functions in php.ini:
`disable_functions="show_source, system, shell_exec, exec"`
A PHP error occurs when opening the JoomGallery configuration.
No error is thrown.
=> Fix error when exec is disabled

administrator/com_joomgallery/layouts/joomla/form/field/subform/repeatable-config/sectionWithPopup.php, administrator/com_joomgallery/tmpl/config/edit.php, administrator/com_joomgallery/tmpl/image/upload.php
Since Joomla 5.1.0 bootstrap.modal javascript library is not loaded automatically anymore. Therefore views using the bootstrap modalbox have to load the library by themselves.
The modalbox is added to the following views:
- Configuration set edit
- Multiple image upload form
=> Add modalbox

plugins/system/joomgallery/src/Extension/Joomgallery.php
This PR fix es issues reported in #226 
There is an additional warning printed out in Joomla 5.x telling that `Undefined array key 0 in C:\Users\Manuel\Documents\GitHub\JG4-dev\plugins\system\joomgallery\src\Extension\Joomgallery.php on line 219`. This warning can  not be solved without loosing functionality in Joomla 4.x. Possible PHP errors in future PHP versions are catched and handled not to loose functionality.
```
Joomla\CMS\Event\Model\AfterCleanCacheEvent::onSetResult(): Argument https://github.com/JoomGalleryfriends/JG4-dev/pull/1 ($value) must be of type bool, array given, called in /joomla-root-verzeichnis/libraries/src/Event/AbstractEvent.php on line 227
```
=> Fix errors in system plugin

administrator/com_joomgallery/src/Extension/MessageTrait.php
This PR fixes and improves the error and logging functionities provided by the JoomGallery extension class.
The following methods are available:
```
// Add debug message
setDebug($txt, $new_line=true, $margin_top=false, $log=false, $name=null)
// Add warning message
setWarning($txt, $new_line=true, $margin_top=false, $log=false, $name=null)
// Add error message
setError($txt, $new_line=true, $margin_top=false, $log=true, $name=null)
// Add a message to a logging file
setLog($txt, $priority = 8, $name = null)
```
With the argument `$log` you can activate to add also a logging entry. So the message will be outputted as well as logged. With `$name` you can choose the filename of the logging file where to output. The default file is `com_joomgallery.log.php`. If you add a logging name the …
=> Update Error/Logging functionalities

plugins/system/joomgallery/src/Extension/Joomgallery.php
This PR addresses issue #234 
An error was thrown when saving a user in J5.x with activated joomgallery system plugin.
=> Fix error in system plugin

administrator/com_joomgallery/src/Extension/MessageTrait.php, administrator/com_joomgallery/src/Model/CategoryModel.php, administrator/com_joomgallery/src/Model/ImageModel.php, administrator/com_joomgallery/src/Service/Messenger/MailMessenger.php
Before this PR `$this->component->addLog(string $txt, $priority = 8, string $name = null)` the second argument needed to be a integer with a proper value for the type of message based on the constants defined in `Joomla\CMS\Log\Log`.
With this PR it is now possible to choose the type of message by providing a string with the proper name of the message type.
**Before this PR**
`$this->component->addLog('My error message', 8, 'jerror')`
which is the same as
`$this->component->addLog('My error message', Log::ERROR, 'jerror')`
**After this PR**
`$this->component->addLog('My error message', 'error', 'jerror')`
Where the old way is still possible.
This fixes the issue reported in PR #239 
>0 Class “Joomgallery\Component\Joomgallery\Administrator\Model\Log” not found
1 () …
=> Simplifying usage of addLog()

administrator/com_joomgallery/forms/category.xml, administrator/com_joomgallery/language/en-GB/com_joomgallery.ini, administrator/com_joomgallery/src/Model/CategoryModel.php, administrator/com_joomgallery/src/Table/CategoryTable.php, administrator/com_joomgallery/tmpl/category/edit.php, media/com_joomgallery/css/admin.css
This PR adds the functionality of the password field in the backend category edit form.
When entering a passord and save the form the new password gets encrypted and saved to database.
If no password is entered in the form field, the old password is retained.
A field called "Remove password" is shown in the edit form when a password is currently set for this category. With this field the password can be removed.
- Test if the password is correctly stored to the database. You should see an encrypted hash in the categories db table.
- Test if the remove password is correctly shown and disabled if not needed.
- Test if the password is retained if you leave the form field empty.
- Test if you can remove the password.
=> Category password field

administrator/com_joomgallery/sql/install.mysql.utf8.sql, administrator/com_joomgallery/sql/updates/mysql/4.0.0.sql
The following setting in the JoomGallery configuration is currently not saved:
`User Settings -> Uploads -> Frontend upload`
Make a new installation, not an update.
Change the field 'Fronted upload' and save your setting.
Check if the correct setting is available after closing and reopening.
=> Add missing field jg_userupload

administrator/com_joomgallery/src/Model/MigrationModel.php
In the migration manager the PHP error `Return value must be of type array` is thrown when trying to continue a migration. Additionally the ACL is done in the wrong way and also there an error is thrown.
This PR fixes this issues in the migration manager.
=> Fix error in migration manager

administrator/com_joomgallery/src/Model/JoomAdminModel.php
This PR fixes issue #268.
There were two errors on top of each other preventing the ordering of records in list views of JoomGallery. This PR fixes this issue for all list views.
**Errors which are fixed:**
- Typo when initializing a batch process in JoomAdminModel
--> Dragndrop sorting uses the batch process of the list model. Thats why sorting failed.
- Error introduced with PR #261 when checking permissions within the JoomAdminModel
--> Therefore ACL checks on canDelete, canEditState failed
=> Fix issues in ListAdminModel

administrator/com_joomgallery/src/Helper/JoomHelper.php
This PR fixes the issue reported in #213 
When compatibility mode activated, the old image type names gets forewarded to the new ones. This way the old image source paths should work again.
**Old (JG3)**
index.php?option=com_joomgallery&view=image&format=raw&id=123&type=img
**New (JG4)**
index.php?option=com_joomgallery&view=image&format=raw&id=123&type=detail
=> Change of the 'Image types' names

plugins/system/joomgallery/src/Extension/Joomgallery.php, plugins/system/joomowner/src/Extension/JoomgalleryOwner.php
This PR gets rid of these messages always appearing in Joomla 5.x when JoomGallery system plugins are activated.
=> Remove PHP warnings from plugins

administrator/com_joomgallery/language/en-GB/com_joomgallery.ini, administrator/com_joomgallery/src/Model/ImageModel.php, administrator/com_joomgallery/src/Service/FileManager/FileManager.php, administrator/com_joomgallery/src/Service/IMGtools/GDtools.php, administrator/com_joomgallery/src/Service/IMGtools/GifCreator.php, administrator/com_joomgallery/src/Service/IMGtools/IMGtools.php, administrator/com_joomgallery/src/Service/IMGtools/IMtools.php, administrator/com_joomgallery/src/Service/Uploader/Uploader.php
This PR fixes different upload issues reported in the issue tracker of this repository. The following issues have been fixed:
- #107
- #111 
- #118 
- #130 
- #262 
The issus reported in 111 & 118 are only partially solved. In case there is no image processing configured, the original image gets now copied and no changes will be made on it. This ensures that matadata is prevented and filesize is not changed. In case there are any image processing settings set on the original image, this issues still exist.
But at least for issue 111, the metadata service currently beeing developed by @Spoicy will have a fix for that.
Upload multiple different images (different file types like jpg, png, gif, webp). Use some with tarnsparency and some with animations. Test both image processors, Imagemagick …
=> Fixes different upload issues

administrator/com_joomgallery/src/View/JoomGalleryView.php
This PR changes the way development versions are detected. Now version strings containing `dev`, `alpha`, `beta` or `rc` are detected as development versions and will show the hint in the JoomGallery views.
=> Change string to detect development version

administrator/com_joomgallery/src/View/Image/RawView.php, site/com_joomgallery/language/en-GB/com_joomgallery.ini, site/com_joomgallery/src/Model/CategoryModel.php, site/com_joomgallery/src/Model/ImageModel.php, site/com_joomgallery/src/View/Category/HtmlView.php, site/com_joomgallery/src/View/Category/JsonView.php, site/com_joomgallery/src/View/Category/RawView.php, site/com_joomgallery/src/View/Categoryform/HtmlView.php, site/com_joomgallery/src/View/Image/HtmlView.php, site/com_joomgallery/src/View/Image/JpgView.php, site/com_joomgallery/src/View/Image/RawView.php
This PR solves the issue reported in #294 
The following frontend views are affected:
- category (format: html, json, raw)
URL: option=com_joomgallery&view=category&id=<catid>&format=html
- image (format: html, raw)
URL: option=com_joomgallery&view=category&id=<imgid&format=html
In the category view it gets checked, that
- the category is published
- the user has the proper access level for this category
- the category is protected with a password
In the image view it gets checked, that
- the category is published
- the category is protected with a password
- the image is published
- the image is approved
- the user has the proper access level for this image
Images and categories of a protected category can be accessed, even if the password of the parent category is not validated. …
=> Access check for frontend views

administrator/com_joomgallery/src/Model/MigrationModel.php
This PR fixes the issue reported in #298 
The way how the onMigrationBeforeSave event is triggered has to be changed now after PR #292 is merged. In Joomla 5+, we have to use the dedicated events like `Joomla\CMS\Event\Model\BeforeSaveEvent` containing special methods like `getItem()`. The `Joomla\Event\Event` method can not be used anymore in Joomla 5+ while it still has to be used in Joomla 4.x.
In order to support both Joomla versions, we need a switch and both ways of triggering the event. Thanks @joomla/joomla-cms for this additional work ;-)
--> Here you can see now the double work to be done by developers if you want to have backward compatibility!
The migrations should be working again with this PR applied.
=> Fix issue with onMigrationBeforeSave event

media/com_joomgallery/joomla.asset.json, media/com_joomgallery/js/joomgrid.js, site/com_joomgallery/layouts/joomgallery/grids/images.php, site/com_joomgallery/layouts/joomgallery/grids/subcategories.php, site/com_joomgallery/tmpl/category/default_cat.php
This PR does not change any functionality, but cleans up the code of the category view template and make it reusable.
When applying this PR there are the following files newly in the JoomGallery filesystem:
- **_media/com_joomgallery/js/joomgrid.js_**
containing the majority of the before inline javascript code
- **_components/com_joomgallery/layouts/joomgallery/grids/subcategories.php_**
containing the html template for a grid of subcategory-images
- **_components/com_joomgallery/layouts/joomgallery/grids/images.php_**
containing the html template for a grid of images
This paves the way for easy creation of grid views at various locations. E.g. content plugin, category module, ...
The category view should act the same way as before and no errors should appear
=> Layouts for Category view

administrator/com_joomgallery/src/Table/JoomTableTrait.php
This PR places back the method getPreviousOrder() into the JoomTableTrait, which was lost in a rebase process.
=> Add getPreviousOrder() method

administrator/com_joomgallery/src/Field/JgcategoryField.php, administrator/com_joomgallery/src/Field/JgimageField.php, administrator/com_joomgallery/src/Field/JglistField.php, administrator/com_joomgallery/src/Field/JgtagField.php, administrator/com_joomgallery/src/Helper/JoomHelper.php, administrator/com_joomgallery/src/View/Image/RawView.php, media/com_joomgallery/css/admin.css, media/com_joomgallery/js/field-category.js, media/com_joomgallery/js/field-image.js, site/com_joomgallery/layouts/joomla/form/field/jgcategory.php, site/com_joomgallery/layouts/joomla/form/field/jgimage.php, site/com_joomgallery/layouts/joomla/form/field/jgtag.php, site/com_joomgallery/layouts/joomla/form/field/radio/configbtns.php, site/com_joomgallery/src/Service/DefaultRouter.php, site/com_joomgallery/src/View/Image/RawView.php
This PR adds the possibility to use the JoomGallery specific fields in forms outside of the JoomGallery component.
It affects the fields of type:
- jgcategory
- jgimage
- jglist
- jgtag
- Visit the edit forms of image, category, tag in the backend. The form fields still have to be correctly shown.
=> Allow external usage of JG Fields

administrator/com_joomgallery/src/Controller/JoomAdminController.php, administrator/com_joomgallery/src/Controller/JoomFormController.php, administrator/com_joomgallery/src/Controller/TagsController.php, administrator/com_joomgallery/src/Extension/MessageTrait.php, administrator/com_joomgallery/src/Field/JgtagField.php, administrator/com_joomgallery/src/Model/TagsModel.php, administrator/com_joomgallery/src/Table/ImageTable.php
Before the PR, the Tags-Field in the Image edit form didnt behave correctly. This PR fixes this issues.
- A JS error is thrown when searching for tags
- When adding a new tag, the tag was not saved when saving the image
- Open the image edit form of an existing Image
- Open the browser console and observe the `console` as well as the `network` tab
- Search for tags in the tag field
- Create new tags by hit enter if there are no search results
- Save image form and check if all tags are correctly listed in the tags field and there are no errors (PHP and JS)
=> Fix issues with JgTagField

administrator/com_joomgallery/language/en-GB/com_joomgallery.ini, administrator/com_joomgallery/src/Model/MigrationModel.php, administrator/com_joomgallery/src/Service/FileManager/FileManager.php, administrator/com_joomgallery/src/Service/FileManager/FileManagerInterface.php, administrator/com_joomgallery/src/Service/Migration/Scripts/Jg3ToJg4.php
This PR adjusts the way error logging is done during migration. This will add some important information when there is an error happening in the file manager service.
- Migration should still work as before
- In case of an error when dealing with the filesystem, the log file should contain more and useful information.
=> Imporve error logging during migration

site/com_joomgallery/language/en-GB/com_joomgallery.ini, site/com_joomgallery/tmpl/category/default_cat.php, site/com_joomgallery/tmpl/gallery/default.php, site/com_joomgallery/tmpl/image/default.php
In some places in the frontend, 'fixed texts' are displayed instead of language constants. Therefore, these places cannot be translated in other languages.
This PR adds language constants in the following places:
'Back to: Parent Category' -> COM_JOOMGALLERY_CATEGORY_BACK_TO_PARENT
'No elements in this category...' -> COM_JOOMGALLERY_CATEGORY_NO_ELEMENTS
'No images in the gallery...' -> COM_JOOMGALLERY_GALLERY_NO_IMAGES
'Back to: Category' -> COM_JOOMGALLERY_IMAGE_BACK_TO_CATEGORY
=> Add language constants

administrator/com_joomgallery/language/en-GB/com_joomgallery.ini, administrator/com_joomgallery/src/Model/ImageModel.php, administrator/com_joomgallery/src/View/Category/HtmlView.php, administrator/com_joomgallery/tmpl/category/edit.php
This PR adds an error handling for the issue #342.
If you try to move or copy an image into a category with another filesystem, you will get an error and the save process is cancelled. This is not a proper fix, but it prevents corrupt datasets. For a proper fix, the filesystem service would have to be extended to support multiple filesystems. This can be implemented in a later release...
- When editing an existing category, the parameter field `jg_filesystem` has to be deactivated
- When changing the category of an existing image to a category having another filesystem set in its configuration, you will get an error and the image will not be saved.
- When copying a existing image and select a category having another filesystem set in its configuration, you will get an error and the image …
=> Fix: Move image to another filesystem

site/com_joomgallery/src/Model/CategoryModel.php, site/com_joomgallery/src/Model/GalleryModel.php
This PR fixes the issue reported in #355
The ordering configuration parameter `jg_category_view_ord_images` and `jg_gallery_view_ordering` should now have an effect on the ordering in the category and the gallery view in the frontend.
=> Sorting images category & gallery view

site/com_joomgallery/layouts/joomgallery/content/metadata.php, site/com_joomgallery/src/Model/CategoryModel.php, site/com_joomgallery/src/Model/GalleryModel.php
This PR fixes the fowllowing two frontend errors:
- Detail view: PHP error when having an array in some metadata values
- Category & Gallery view: PHP error when activating `Use real paths` in component configurations
(#356)
- [This image](https://drive.google.com/file/d/1hnef5zEADPxv7GFAuILAxLnbEOsr9Zwu/view?usp=sharing) creates an error in the single image view when this PR is not applied. No error with this PR.
- Activate `Use real paths` in component configurations and visit a category view containing at least one image.
=> Fix two frontend PHP errors

site/com_joomgallery/src/Model/CategoryModel.php, site/com_joomgallery/src/Model/ImageModel.php
This PR solves an issue in a 3rd party extension.
If you try to load multiple images or categories using its ItemModels (ImageModel or CategoryModel) in the fronted, the same item gets loaded multiple times instead of the different ones.
Click through the Frontend views. Everything should work as before without errors.
=> Fix issue when loading multiple items

administrator/com_joomgallery/language/en-GB/com_joomgallery.ini, administrator/com_joomgallery/src/Controller/JoomAdminController.php, administrator/com_joomgallery/src/Controller/JoomFormController.php, administrator/com_joomgallery/src/Controller/MigrationController.php, administrator/com_joomgallery/src/Extension/MessageTrait.php, administrator/com_joomgallery/src/Service/Migration/Migration.php, administrator/com_joomgallery/src/Service/Migration/Scripts/Jg3ToJg4.php
This PR adds the functionality of deleting source directories and tables at the end of the migration (step 4).
See issue #359
AT step 4 of the migration, the Button `Remove source data` now actually removes the source data.
=> Add deleteSource() method to Migration script

media/com_joomgallery/js/joomgrid.js
This pr removes javascript errors when using the justified layout in combination with an empty category. It also removes errors for infinite scroll and load more if the category has no images.
=> fix javascript errors [imgJust]

administrator/com_joomgallery/src/Field/ExternalconfigField.php
This issue fixes an error reported by a JoomGallery user reported us that the configuration set edit view can not be opened when the language debugging is active.
After applying this PR you can now open the "Global Configuration" without error even if Joomla & Language debugging is activated.
=> Fix issue with xml path

administrator/com_joomgallery/src/Service/Migration/Migration.php, administrator/com_joomgallery/src/Service/Migration/Scripts/Jg3ToJg4.php
This PR fixes the issue reported in issue #378.
It seems that there was a change in Joomla 5.2.4 onwards wich requires to have an integer value as the `asset_id` when creating a new asset entry. Therefore now we introduce `asset_id = 0` instead of `asset_id = null`.
=> Fix issue with asset_id during migration

administrator/com_joomgallery/forms/filter_categories.xml, administrator/com_joomgallery/forms/filter_images.xml, administrator/com_joomgallery/forms/filter_tags.xml, administrator/com_joomgallery/src/Model/CategoriesModel.php, administrator/com_joomgallery/src/Model/ImagesModel.php
Possible fix for https://github.com/JoomGalleryfriends/JG4-dev/issues/382
This PR adds the missing language filters for images, categories. tags
=> Add language filter
