administrator/com_joomgallery/forms/category.xml
administrator/com_joomgallery/forms/image.xml
administrator/com_joomgallery/forms/tag.xml
administrator/com_joomgallery/src/Model/CategoryModel.php
administrator/com_joomgallery/src/Model/ImageModel.php
administrator/com_joomgallery/src/Model/TagModel.php
administrator/com_joomgallery/tmpl/categories/default.php
administrator/com_joomgallery/tmpl/images/default.php
administrator/com_joomgallery/tmpl/tags/default.php

Fixes the bug reported in issue #5

fix language field behavior

---

administrator/com_joomgallery/includes/defines.php
administrator/com_joomgallery/src/Controller/CategoriesController.php
administrator/com_joomgallery/src/Controller/ConfigsController.php
administrator/com_joomgallery/src/Controller/FaultiesController.php
administrator/com_joomgallery/src/Controller/ImagesController.php
administrator/com_joomgallery/src/Controller/TagsController.php
administrator/com_joomgallery/src/Helper/JoomHelper.php
administrator/com_joomgallery/src/Model/CategoriesModel.php
administrator/com_joomgallery/src/Model/CategoryModel.php
administrator/com_joomgallery/src/Model/ConfigModel.php
administrator/com_joomgallery/src/Model/ConfigsModel.php
administrator/com_joomgallery/src/Model/FaultiesModel.php
administrator/com_joomgallery/src/Model/ImageModel.php
administrator/com_joomgallery/src/Model/ImagesModel.php
administrator/com_joomgallery/src/Model/ImagetypeModel.php
administrator/com_joomgallery/src/Model/ImagetypesModel.php
administrator/com_joomgallery/src/Model/JoomListModel.php
administrator/com_joomgallery/src/Model/TagModel.php
administrator/com_joomgallery/src/Model/TagsModel.php
administrator/com_joomgallery/src/Table/CategoryTable.php
administrator/com_joomgallery/src/Table/ConfigTable.php
administrator/com_joomgallery/src/Table/ImageTable.php
administrator/com_joomgallery/src/Table/ImagetypeTable.php
administrator/com_joomgallery/src/Table/TagTable.php
script.php

Fixes the bug reported in issue https://github.com/JoomGalleryfriends/JG4-dev/issues/4
With this PR it is now possible to install the component on linux systems.

Stable installation/update and deinstallation

---

administrator/com_joomgallery/forms/filter_categories.xml
administrator/com_joomgallery/forms/filter_configs.xml
administrator/com_joomgallery/forms/filter_faulties.xml
administrator/com_joomgallery/forms/filter_images.xml
administrator/com_joomgallery/forms/filter_tags.xml
administrator/com_joomgallery/src/Model/ImagesModel.php
administrator/com_joomgallery/src/View/Categories/HtmlView.php
administrator/com_joomgallery/src/View/Configs/HtmlView.php
administrator/com_joomgallery/src/View/Faulties/HtmlView.php
administrator/com_joomgallery/src/View/Images/HtmlView.php
administrator/com_joomgallery/src/View/Tags/HtmlView.php
administrator/com_joomgallery/tmpl/categories/default.php
administrator/com_joomgallery/tmpl/images/default.php

Fixes the bug that ordering was not possible in admin list views. Before this PR, selecting a different ordering in the list views did not affect the ordering of the items.

fix ordering in list views

---

administrator/com_joomgallery/forms/filter_tags.xml
administrator/com_joomgallery/forms/tag.xml
administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
administrator/com_joomgallery/sql/install.mysql.utf8.sql
administrator/com_joomgallery/src/Model/TagsModel.php
administrator/com_joomgallery/src/Table/TagTable.php
administrator/com_joomgallery/src/View/Tags/HtmlView.php
administrator/com_joomgallery/tmpl/tag/edit.php
administrator/com_joomgallery/tmpl/tags/default.php

Basic functionality of Tags Manager realized. It is now possible to use all the buttons and functionalities of the Tags Manager.
- Click all the buttons, links and try everything out that is possible with the GUI inside the Tags Manager.

Tags manager

---

administrator/com_joomgallery/forms/category.xml
administrator/com_joomgallery/forms/image.xml
administrator/com_joomgallery/forms/tag.xml

Changes the layout of yes/no fields in edit forms for images, categories and tags.
Adds a character counter for the meta description for images and categories like in Joomla.

Changes layouts and adds character counter in edit forms

---

.gitignore
administrator/com_joomgallery/src/Model/TagsModel.php
site/com_joomgallery/src/Service/Router.php

Change some code to make the batch copy and the first frontend view working

Simple Bugs

---

administrator/com_joomgallery/config.xml
administrator/com_joomgallery/forms/subform_catparams.xml
administrator/com_joomgallery/forms/subform_imageparams.xml
administrator/com_joomgallery/language/en-GB/com_joomgallery.ini
administrator/com_joomgallery/layouts/joomla/form/field/radio/configbtns.php
administrator/com_joomgallery/src/Service/Config/Config.php
administrator/com_joomgallery/src/Service/Config/ConfigInterface.php
administrator/com_joomgallery/src/Service/Config/ConfigServiceInterface.php
administrator/com_joomgallery/src/Service/Config/ConfigServiceTrait.php
administrator/com_joomgallery/src/Service/Config/DefaultConfig.php
administrator/com_joomgallery/tmpl/category/edit.php
administrator/com_joomgallery/tmpl/image/edit.php

This PR adds the global calculated parameter in the Parameters tab of the "Edit Image" and "Edit Category" view. The dynamic calculation of the global parameter is done with the same logic which will later be applied but without taking into account parameters set by the Menu Item. In addition, the parameters are carried out on the basis of the current user. Therefore the calculated value can change based on the user group you are in...

Globally calculated parameter in edit views

---

administrator/com_joomgallery/src/Service/Uploader/UploaderServiceTrait.php

Fix for issue https://github.com/JoomGalleryfriends/JG4-dev/issues/115
Then the mass upload with uppy works should work again.

Fix mass upload with uppy

---

administrator/com_joomgallery/tmpl/configs/default.php

Fix for issue https://github.com/JoomGalleryfriends/JG4-dev/issues/117

Fix for configuration check-in

---

media/com_joomgallery/css/site.css

Centering the title of the image in the tumbs of the category view.

center thumb caption

---

.gitignore
administrator/com_joomgallery/forms/subform_catparams.xml
administrator/com_joomgallery/forms/subform_imageparams.xml
administrator/com_joomgallery/layouts/joomla/form/field/configlist.php
administrator/com_joomgallery/layouts/joomla/form/field/radio/configbtns.php
administrator/com_joomgallery/src/Field/JgMenuitemTrait.php
administrator/com_joomgallery/src/Field/JglistField.php
administrator/com_joomgallery/src/Field/JgnumberField.php
administrator/com_joomgallery/src/Field/JgradioField.php
administrator/com_joomgallery/src/Field/JgtextField.php
administrator/com_joomgallery/src/Helper/ConfigHelper.php
joomgallery.xml
media/com_joomgallery/css/site.css
site/com_joomgallery/layouts/joomla/form/field/configlist.php
site/com_joomgallery/layouts/joomla/pagination/links.php
site/com_joomgallery/layouts/joomla/searchtools/default.php
site/com_joomgallery/src/Model/CategoryModel.php
site/com_joomgallery/src/View/Category/HtmlView.php
site/com_joomgallery/tmpl/category/default.php

This PR adds form fields for configuration params that are inherited through the component global config sets, categories, images, menu items.
- jglist (for selections)
Dropdown list with first entry beeing "Use Global (value)"
- jgradio (for yes, no selections)
Three radio buttons with first button beeing "Use Global (value)"
- jgtext (for free text input)
Text field with hint beeing the global value
- jgnumber (for number input)
Number field with hint beeing the global value
If you want the global inherited value to be calcultaed and displayed, its important to add the `useglobal="true"` attribute to the field definition in the XML.
Example of the jgradio field without predefined value for the global option. By default the global option value is an empty string "".
Example of the …

Add configuration dependent form fields

---

administrator/com_joomgallery/forms/config.xml

Fix for issue https://github.com/JoomGalleryfriends/JG4-dev/issues/227
Open a existing JoomGallery configuration and klick on 'Reset' and confirm the action.
A PHP error occurs.
No error is thrown.

Fix error when reset config

---

administrator/com_joomgallery/services/provider.php

Fixes the error unexpected end of file which was unintentionally introduced during the rebasing.

Fix php error unexpected end of file

---

administrator/com_joomgallery/includes/rules.php
administrator/com_joomgallery/src/Service/Access/Access.php
administrator/com_joomgallery/src/View/Categories/HtmlView.php
administrator/com_joomgallery/src/View/Configs/HtmlView.php
administrator/com_joomgallery/src/View/Images/HtmlView.php
administrator/com_joomgallery/src/View/Tags/HtmlView.php
administrator/com_joomgallery/tmpl/categories/default.php
administrator/com_joomgallery/tmpl/configs/default.php
administrator/com_joomgallery/tmpl/images/default.php
administrator/com_joomgallery/tmpl/tags/default.php

This PR fixes the visability of the buttons in the list views (Issue #237 ).
I had to adjust the access service for that. So please check that the permissions are still correct.

Button visability in list views

---

site/com_joomgallery/tmpl/category/default_cat.php

Restores all changes from  Lightgallery thumbnails #263. Please merge quickly for future changes.

Restoring the changes from #263

---

administrator/com_joomgallery/src/Controller/ImageController.php

This PR fixed the reported issue #245.
It is now possible again to replace an image file.

Fix issue when replace image

---

administrator/com_joomgallery/src/Service/Access/Access.php
administrator/com_joomgallery/src/Service/Migration/Migration.php

This changes code so please check carefully

lenght > length

---

administrator/com_joomgallery/src/Model/CategoriesModel.php

Fix issue with category list filter

---

administrator/com_joomgallery/src/Model/JoomAdminModel.php
administrator/com_joomgallery/src/Service/Access/Access.php
administrator/com_joomgallery/src/Service/Access/AccessInterface.php
administrator/com_joomgallery/src/Service/Access/Base/AccessOwn.php
media/com_joomgallery/css/site.css
site/com_joomgallery/layouts/joomgallery/content/metadata.php
site/com_joomgallery/layouts/joomgallery/content/tags.php
site/com_joomgallery/src/Model/ImageModel.php
site/com_joomgallery/tmpl/image/default.php

This PR adds a display for Tags and Custom Fields for the Simgle Image View in the frontend.

Tags & Fields for Simgle Image View

---

administrator/com_joomgallery/sql/install.mysql.utf8.sql
administrator/com_joomgallery/sql/updates/mysql/4.0.0.sql
site/com_joomgallery/layouts/joomgallery/grids/subcategories.php

Possible fix for https://github.com/JoomGalleryfriends/JG4-dev/issues/353
While checking I noticed that the column 'thumbnail' in the table #__joomgallery_categories has a wrong data type. The correct one should be 'int'. This will also be corrected.
Create several categories. Assign a fixed thumbnail for some categories and for others not.
Change the 'Random image' setting in the configuration and check in the frontend whether the category thumbnails are displayed correctly.

Fix random image error

---

administrator/com_joomgallery/forms/config.xml
site/com_joomgallery/src/Model/CategoryModel.php
site/com_joomgallery/src/View/Category/HtmlView.php
site/com_joomgallery/tmpl/category/default.xml
site/com_joomgallery/tmpl/category/default_cat.php

This pull request brings pagination for the standard display. Load more and infinite scroll will follow in a later pull request.
this addresses issue #347

Default pagination for subcategories

---

media/com_joomgallery/css/site.css
media/com_joomgallery/js/joomgrid.js

The justified layout now also works smoothly with the standard pagination. Before the pull request, the layout was displayed incorrectly after clicking on the next page.

Bug fix for justified layout

---

administrator/com_joomgallery/src/View/Test/HtmlView.php

This PR adds a new view to the backend:
/administrator/index.php?option=com_joomgallery&view=test
This is a complete empty view which allows for easier PHP testing.
--> Low prio!!

Add test view in the backend

---

media/com_joomgallery/css/site.css
site/com_joomgallery/layouts/joomgallery/grids/images.php

Show image description under title in lightgallery.

Lightgallery image description

---

administrator/com_joomgallery/layouts/joomla/form/renderfield.php
administrator/com_joomgallery/tmpl/control/default.php

This PR adds the changes who where made to the RC version also to the general development branch.
- Add the possibility to hide form fields by adding the term `hidden` to the xml field attribute `class`.
- Exchange the PayPal donation Button link.
This changes is also included in PR #381.

Apply changes from RC PR

---

joomgallery.xml
plugins/privacy/joomgallery/joomgallery.xml
plugins/system/joomgallery/joomgallery.xml
plugins/system/joomowner/joomowner.xml

This PR is to prepare the JG4 for its stable release.
- Check that the message about the development version is gone.
```This version of JoomGallery is still under development. ...```

Prepare stable release
